# Generated by Django 5.1 on 2024-08-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Precio', models.CharField(max_length=50)),
                ('Tipo', models.CharField(max_length=50)),
                ('Imagen', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
